services:
  # Keycloak para desenvolvimento
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: my-finance-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    ports:
      - "7080:7080"
    depends_on:
      - postgres
    volumes:
      - ./dist_keycloak:/opt/keycloak/providers
    command: start-dev

  # PostgreSQL para Keycloak
  postgres:
    image: postgres:15
    container_name: my-finance-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "8000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: my-finance-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 